"""empty message

Revision ID: 1f739f81a20
Revises: None
Create Date: 2015-07-12 09:25:06.087794

"""

# revision identifiers, used by Alembic.
revision = '1f739f81a20'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
